### ISSUE TITLE
Delete existing data before running

### ISSUE THREAD

**Issue by fbertsch** [mozilla/leanplum-data-export#9]
If the job fails before deleting the GCS data, it will remain for the next run. We should delete the data before running to ensure that data isn't loaded multiple times.

**Comment by BenWu** [comment]
Isn't that what this line does? https://github.com/mozilla/leanplum-data-export/blob/862ef4adbc993d7af9965fd43cb654a9f2e87c47/leanplum_data_export/export.py#L94

Doesn't the `save_files` function delete the relevant files in the bucket before uploading the new ones?

**Comment by fbertsch** [comment]
> Isn't that what this line does?
> 
> https://github.com/mozilla/leanplum-data-export/blob/862ef4adbc993d7af9965fd43cb654a9f2e87c47/leanplum_data_export/export.py#L94
> 
> Doesn't the `save_files` function delete the relevant files in the bucket before uploading the new ones?

It definitely is. Looks like I was a bit late on this one :)
